### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dispatch')

### ISSUE THREAD

**Issue by ediboy-mosaic** [revolver-app/vuex-orm#783]
#### Describe the bug

Getting `TypeError: Cannot read properties of undefined (reading 'dispatch')` issue when running mock api test in Nuxt using [testing library](https://testing-library.com/docs/vue-testing-library/intro/), [msw](https://github.com/mswjs/msw)

#### Steps to reproduce the bug

**My code:**
```
import {render} from '@testing-library/vue'
import '@testing-library/jest-dom'
import {rest} from 'msw'
import {setupServer} from 'msw/node'
import ComponentWithRequest from './ComponentWithRequest'
import VuexORMAxios from '@vuex-orm/plugin-axios'
import VuexORM from '@vuex-orm/core'
import axios from 'axios'

VuexORM.use(VuexORMAxios, {axios})

const server = setupServer(
  rest.get('/brands', (req, res, ctx) => {
    return res(ctx.json({data: []}))
  }),
)

beforeAll(() => server.listen())
afterEach(() => server.resetHandlers())
afterAll(() => server.close())

test('Brands should render properly', async () => {
  const {getByText} = render(ComponentWithRequest)
})
```

**Error:**
```
 TypeError: Cannot read properties of undefined (reading 'dispatch')
        at Function.Object.<anonymous>.Model.dispatch (/home/user/node_modules/@vuex-orm/core/dist/vuex-orm.cjs.js:2817:28)
        at Function.Object.<anonymous>.Model.insertOrUpdate (/home/user/node_modules/@vuex-orm/core/dist/vuex-orm.cjs.js:2901:21)
        at Response.<anonymous> (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:110:64)
        at step (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:61:23)
        at Object.next (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:42:53)
        at /home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:35:71
        at new Promise (<anonymous>)
        at __awaiter (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:31:12)
        at Response.Object.<anonymous>.Response.save (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:88:16)
        at Request.<anonymous> (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:323:55)
        at step (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:61:23)
        at Object.next (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:42:53)
        at /home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:35:71
        at new Promise (<anonymous>)
        at __awaiter (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:31:12)
        at Request.Object.<anonymous>.Request.createResponse (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:309:16)
        at Request.<anonymous> (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:292:52)
        at step (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:61:23)
        at Object.next (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:42:53)
        at fulfilled (/home/user/node_modules/@vuex-orm/plugin-axios/dist/vuex-orm-axios.cjs.js:32:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

#### Expected behaviour

Should pass the test

#### Versions

- Vuex ORM: 0.36.4
- Nuxt: 2.15.7
- msw: 0.43.0
- testing-library/vue: 5.8.3

**Comment by ahmeddabak** [comment]
We started having the same problem after upgrading NodeJS to 18
